// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countConversationParticipants = `-- name: CountConversationParticipants :one
SELECT COUNT(*)
FROM participants p
WHERE p.conversation_id = $1
  AND p.deleted_at IS NULL
`

func (q *Queries) CountConversationParticipants(ctx context.Context, conversationID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countConversationParticipants, conversationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteConversation = `-- name: DeleteConversation :exec
UPDATE conversations
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1
`

func (q *Queries) DeleteConversation(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteConversation, id)
	return err
}

const findUserByUsername = `-- name: FindUserByUsername :one
SELECT id, avatar, name, password, refresh_token, created_at, updated_at, deleted_at FROM users
WHERE name = $1 AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) FindUserByUsername(ctx context.Context, name string) (User, error) {
	row := q.db.QueryRow(ctx, findUserByUsername, name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Avatar,
		&i.Name,
		&i.Password,
		&i.RefreshToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getContacts = `-- name: GetContacts :many

SELECT id, name, avatar
FROM users
WHERE deleted_at IS NULL AND id != $1
ORDER BY name ASC, id ASC
LIMIT $2 OFFSET $3
`

type GetContactsParams struct {
	ID     pgtype.UUID `json:"id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

type GetContactsRow struct {
	ID     pgtype.UUID `json:"id"`
	Name   string      `json:"name"`
	Avatar pgtype.Text `json:"avatar"`
}

// Complex queries for read model
func (q *Queries) GetContacts(ctx context.Context, arg GetContactsParams) ([]GetContactsRow, error) {
	rows, err := q.db.Query(ctx, getContacts, arg.ID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetContactsRow
	for rows.Next() {
		var i GetContactsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Avatar); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getConversationBase = `-- name: GetConversationBase :one
SELECT
    c.id as conversation_id,
    c.created_at,
    c.type,
    c.avatar as group_avatar,
    c.name as group_name,
    c.owner_id as group_owner_id
FROM conversations c
JOIN participants up ON up.conversation_id = c.id
    AND up.user_id = $1
    AND up.deleted_at IS NULL
WHERE c.id = $2
  AND c.deleted_at IS NULL
LIMIT 1
`

type GetConversationBaseParams struct {
	UserID pgtype.UUID `json:"user_id"`
	ID     pgtype.UUID `json:"id"`
}

type GetConversationBaseRow struct {
	ConversationID pgtype.UUID        `json:"conversation_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	Type           int32              `json:"type"`
	GroupAvatar    pgtype.Text        `json:"group_avatar"`
	GroupName      pgtype.Text        `json:"group_name"`
	GroupOwnerID   pgtype.UUID        `json:"group_owner_id"`
}

func (q *Queries) GetConversationBase(ctx context.Context, arg GetConversationBaseParams) (GetConversationBaseRow, error) {
	row := q.db.QueryRow(ctx, getConversationBase, arg.UserID, arg.ID)
	var i GetConversationBaseRow
	err := row.Scan(
		&i.ConversationID,
		&i.CreatedAt,
		&i.Type,
		&i.GroupAvatar,
		&i.GroupName,
		&i.GroupOwnerID,
	)
	return i, err
}

const getConversationIDsByUserID = `-- name: GetConversationIDsByUserID :many
SELECT conversation_id
FROM participants
WHERE user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetConversationIDsByUserID(ctx context.Context, userID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, getConversationIDsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var conversation_id pgtype.UUID
		if err := rows.Scan(&conversation_id); err != nil {
			return nil, err
		}
		items = append(items, conversation_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getConversationMessagesFirstPageRaw = `-- name: GetConversationMessagesFirstPageRaw :many
SELECT
    m.id,
    m.type,
    m.created_at,
    m.conversation_id,
    m.content,
    m.user_id
FROM messages m
WHERE m.conversation_id = $1
  AND m.deleted_at IS NULL
ORDER BY m.created_at DESC, m.id DESC
LIMIT $2
`

type GetConversationMessagesFirstPageRawParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	PageLimit      int32       `json:"page_limit"`
}

type GetConversationMessagesFirstPageRawRow struct {
	ID             pgtype.UUID        `json:"id"`
	Type           int32              `json:"type"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ConversationID pgtype.UUID        `json:"conversation_id"`
	Content        string             `json:"content"`
	UserID         pgtype.UUID        `json:"user_id"`
}

func (q *Queries) GetConversationMessagesFirstPageRaw(ctx context.Context, arg GetConversationMessagesFirstPageRawParams) ([]GetConversationMessagesFirstPageRawRow, error) {
	rows, err := q.db.Query(ctx, getConversationMessagesFirstPageRaw, arg.ConversationID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetConversationMessagesFirstPageRawRow
	for rows.Next() {
		var i GetConversationMessagesFirstPageRawRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.CreatedAt,
			&i.ConversationID,
			&i.Content,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getConversationMessagesPageRaw = `-- name: GetConversationMessagesPageRaw :many
SELECT
    m.id,
    m.type,
    m.created_at,
    m.conversation_id,
    m.content,
    m.user_id
FROM messages m
WHERE m.conversation_id = $1
  AND m.deleted_at IS NULL
  AND (m.created_at, m.id) < (
    $2::timestamptz,
    $3::uuid
  )
ORDER BY m.created_at DESC, m.id DESC
LIMIT $4
`

type GetConversationMessagesPageRawParams struct {
	ConversationID  pgtype.UUID        `json:"conversation_id"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
	PageLimit       int32              `json:"page_limit"`
}

type GetConversationMessagesPageRawRow struct {
	ID             pgtype.UUID        `json:"id"`
	Type           int32              `json:"type"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ConversationID pgtype.UUID        `json:"conversation_id"`
	Content        string             `json:"content"`
	UserID         pgtype.UUID        `json:"user_id"`
}

func (q *Queries) GetConversationMessagesPageRaw(ctx context.Context, arg GetConversationMessagesPageRawParams) ([]GetConversationMessagesPageRawRow, error) {
	rows, err := q.db.Query(ctx, getConversationMessagesPageRaw,
		arg.ConversationID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetConversationMessagesPageRawRow
	for rows.Next() {
		var i GetConversationMessagesPageRawRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.CreatedAt,
			&i.ConversationID,
			&i.Content,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDirectConversationBetweenUsers = `-- name: GetDirectConversationBetweenUsers :one
SELECT c.id, c.type, c.name, c.avatar, c.owner_id, c.created_at, c.updated_at, c.deleted_at
FROM conversations c
JOIN participants p1 ON p1.conversation_id = c.id AND p1.user_id = $1
JOIN participants p2 ON p2.conversation_id = c.id AND p2.user_id = $2
WHERE c.type = 1
  AND c.deleted_at IS NULL
  AND p1.deleted_at IS NULL
  AND p2.deleted_at IS NULL
LIMIT 1
`

type GetDirectConversationBetweenUsersParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	UserID_2 pgtype.UUID `json:"user_id_2"`
}

func (q *Queries) GetDirectConversationBetweenUsers(ctx context.Context, arg GetDirectConversationBetweenUsersParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, getDirectConversationBetweenUsers, arg.UserID, arg.UserID_2)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.Avatar,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDirectConversationOtherUser = `-- name: GetDirectConversationOtherUser :many
SELECT u.id, u.name, u.avatar
FROM participants op
JOIN users u ON u.id = op.user_id
WHERE op.conversation_id = $1
  AND op.user_id <> $2
  AND op.deleted_at IS NULL
  AND u.deleted_at IS NULL
ORDER BY op.created_at ASC
LIMIT 1
`

type GetDirectConversationOtherUserParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	UserID         pgtype.UUID `json:"user_id"`
}

type GetDirectConversationOtherUserRow struct {
	ID     pgtype.UUID `json:"id"`
	Name   string      `json:"name"`
	Avatar pgtype.Text `json:"avatar"`
}

func (q *Queries) GetDirectConversationOtherUser(ctx context.Context, arg GetDirectConversationOtherUserParams) ([]GetDirectConversationOtherUserRow, error) {
	rows, err := q.db.Query(ctx, getDirectConversationOtherUser, arg.ConversationID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDirectConversationOtherUserRow
	for rows.Next() {
		var i GetDirectConversationOtherUserRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Avatar); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getParticipantsByConversationID = `-- name: GetParticipantsByConversationID :many
SELECT u.id, u.name, u.avatar
FROM users u
JOIN participants p ON p.user_id = u.id
WHERE p.conversation_id = $1
  AND p.deleted_at IS NULL
  AND u.deleted_at IS NULL
ORDER BY u.name ASC, u.id ASC
LIMIT $2 OFFSET $3
`

type GetParticipantsByConversationIDParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	Limit          int32       `json:"limit"`
	Offset         int32       `json:"offset"`
}

type GetParticipantsByConversationIDRow struct {
	ID     pgtype.UUID `json:"id"`
	Name   string      `json:"name"`
	Avatar pgtype.Text `json:"avatar"`
}

func (q *Queries) GetParticipantsByConversationID(ctx context.Context, arg GetParticipantsByConversationIDParams) ([]GetParticipantsByConversationIDRow, error) {
	rows, err := q.db.Query(ctx, getParticipantsByConversationID, arg.ConversationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetParticipantsByConversationIDRow
	for rows.Next() {
		var i GetParticipantsByConversationIDRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Avatar); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPotentialInvitees = `-- name: GetPotentialInvitees :many
SELECT u.id, u.name, u.avatar
FROM users u
WHERE u.deleted_at IS NULL
  AND NOT EXISTS (
    SELECT 1
    FROM participants p
    WHERE p.conversation_id = $1
      AND p.user_id = u.id
      AND p.deleted_at IS NULL
  )
ORDER BY u.name ASC, u.id ASC
LIMIT $2 OFFSET $3
`

type GetPotentialInviteesParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	Limit          int32       `json:"limit"`
	Offset         int32       `json:"offset"`
}

type GetPotentialInviteesRow struct {
	ID     pgtype.UUID `json:"id"`
	Name   string      `json:"name"`
	Avatar pgtype.Text `json:"avatar"`
}

func (q *Queries) GetPotentialInvitees(ctx context.Context, arg GetPotentialInviteesParams) ([]GetPotentialInviteesRow, error) {
	rows, err := q.db.Query(ctx, getPotentialInvitees, arg.ConversationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPotentialInviteesRow
	for rows.Next() {
		var i GetPotentialInviteesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Avatar); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, avatar, name, password, refresh_token, created_at, updated_at, deleted_at FROM users
WHERE id = $1 AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Avatar,
		&i.Name,
		&i.Password,
		&i.RefreshToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserConversationsFirstPage = `-- name: GetUserConversationsFirstPage :many
WITH paged_conversations AS (
    SELECT
        c.id,
        c.created_at,
        c.type,
        c.avatar,
        c.name
    FROM conversations c
    JOIN participants p ON p.conversation_id = c.id
      AND p.user_id = $1
      AND p.deleted_at IS NULL
    WHERE c.deleted_at IS NULL
    ORDER BY c.created_at DESC, c.id DESC
    LIMIT $2
)
SELECT
    pc.id as conversation_id,
    pc.created_at,
    pc.type,
    lm.id as message_id,
    lm.type as message_type,
    lm.content as message_content,
    lm.created_at as message_created_at,
    lm.user_id as message_user_id,
    mu.name as message_user_name,
    mu.avatar as message_user_avatar,
    pc.avatar as group_avatar,
    pc.name as group_name,
    ou.id as other_user_id,
    COALESCE(ou.name, '') as other_user_name,
    ou.avatar as other_user_avatar
FROM paged_conversations pc
LEFT JOIN LATERAL (
    SELECT m.id, m.type, m.content, m.created_at, m.user_id
    FROM messages m
    WHERE m.conversation_id = pc.id
      AND m.deleted_at IS NULL
    ORDER BY m.created_at DESC, m.id DESC
    LIMIT 1
) lm ON TRUE
LEFT JOIN users mu ON mu.id = lm.user_id
  AND mu.deleted_at IS NULL
LEFT JOIN LATERAL (
    SELECT u.id, u.name, u.avatar
    FROM participants op
    JOIN users u ON u.id = op.user_id
    WHERE op.conversation_id = pc.id
      AND op.user_id <> $1
      AND op.deleted_at IS NULL
      AND u.deleted_at IS NULL
    ORDER BY op.created_at ASC
    LIMIT 1
) ou ON TRUE
ORDER BY pc.created_at DESC, pc.id DESC
`

type GetUserConversationsFirstPageParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	PageLimit int32       `json:"page_limit"`
}

type GetUserConversationsFirstPageRow struct {
	ConversationID    pgtype.UUID        `json:"conversation_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	Type              int32              `json:"type"`
	MessageID         pgtype.UUID        `json:"message_id"`
	MessageType       int32              `json:"message_type"`
	MessageContent    string             `json:"message_content"`
	MessageCreatedAt  pgtype.Timestamptz `json:"message_created_at"`
	MessageUserID     pgtype.UUID        `json:"message_user_id"`
	MessageUserName   pgtype.Text        `json:"message_user_name"`
	MessageUserAvatar pgtype.Text        `json:"message_user_avatar"`
	GroupAvatar       pgtype.Text        `json:"group_avatar"`
	GroupName         pgtype.Text        `json:"group_name"`
	OtherUserID       pgtype.UUID        `json:"other_user_id"`
	OtherUserName     string             `json:"other_user_name"`
	OtherUserAvatar   pgtype.Text        `json:"other_user_avatar"`
}

func (q *Queries) GetUserConversationsFirstPage(ctx context.Context, arg GetUserConversationsFirstPageParams) ([]GetUserConversationsFirstPageRow, error) {
	rows, err := q.db.Query(ctx, getUserConversationsFirstPage, arg.UserID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserConversationsFirstPageRow
	for rows.Next() {
		var i GetUserConversationsFirstPageRow
		if err := rows.Scan(
			&i.ConversationID,
			&i.CreatedAt,
			&i.Type,
			&i.MessageID,
			&i.MessageType,
			&i.MessageContent,
			&i.MessageCreatedAt,
			&i.MessageUserID,
			&i.MessageUserName,
			&i.MessageUserAvatar,
			&i.GroupAvatar,
			&i.GroupName,
			&i.OtherUserID,
			&i.OtherUserName,
			&i.OtherUserAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserConversationsPage = `-- name: GetUserConversationsPage :many
WITH paged_conversations AS (
    SELECT
        c.id,
        c.created_at,
        c.type,
        c.avatar,
        c.name
    FROM conversations c
    JOIN participants p ON p.conversation_id = c.id
      AND p.user_id = $1
      AND p.deleted_at IS NULL
    WHERE c.deleted_at IS NULL
      AND (c.created_at, c.id) < (
        $2::timestamptz,
        $3::uuid
      )
    ORDER BY c.created_at DESC, c.id DESC
    LIMIT $4
)
SELECT
    pc.id as conversation_id,
    pc.created_at,
    pc.type,
    lm.id as message_id,
    lm.type as message_type,
    lm.content as message_content,
    lm.created_at as message_created_at,
    lm.user_id as message_user_id,
    mu.name as message_user_name,
    mu.avatar as message_user_avatar,
    pc.avatar as group_avatar,
    pc.name as group_name,
    ou.id as other_user_id,
    COALESCE(ou.name, '') as other_user_name,
    ou.avatar as other_user_avatar
FROM paged_conversations pc
LEFT JOIN LATERAL (
    SELECT m.id, m.type, m.content, m.created_at, m.user_id
    FROM messages m
    WHERE m.conversation_id = pc.id
      AND m.deleted_at IS NULL
    ORDER BY m.created_at DESC, m.id DESC
    LIMIT 1
) lm ON TRUE
LEFT JOIN users mu ON mu.id = lm.user_id
  AND mu.deleted_at IS NULL
LEFT JOIN LATERAL (
    SELECT u.id, u.name, u.avatar
    FROM participants op
    JOIN users u ON u.id = op.user_id
    WHERE op.conversation_id = pc.id
      AND op.user_id <> $1
      AND op.deleted_at IS NULL
      AND u.deleted_at IS NULL
    ORDER BY op.created_at ASC
    LIMIT 1
) ou ON TRUE
ORDER BY pc.created_at DESC, pc.id DESC
`

type GetUserConversationsPageParams struct {
	UserID          pgtype.UUID        `json:"user_id"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
	PageLimit       int32              `json:"page_limit"`
}

type GetUserConversationsPageRow struct {
	ConversationID    pgtype.UUID        `json:"conversation_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	Type              int32              `json:"type"`
	MessageID         pgtype.UUID        `json:"message_id"`
	MessageType       int32              `json:"message_type"`
	MessageContent    string             `json:"message_content"`
	MessageCreatedAt  pgtype.Timestamptz `json:"message_created_at"`
	MessageUserID     pgtype.UUID        `json:"message_user_id"`
	MessageUserName   pgtype.Text        `json:"message_user_name"`
	MessageUserAvatar pgtype.Text        `json:"message_user_avatar"`
	GroupAvatar       pgtype.Text        `json:"group_avatar"`
	GroupName         pgtype.Text        `json:"group_name"`
	OtherUserID       pgtype.UUID        `json:"other_user_id"`
	OtherUserName     string             `json:"other_user_name"`
	OtherUserAvatar   pgtype.Text        `json:"other_user_avatar"`
}

func (q *Queries) GetUserConversationsPage(ctx context.Context, arg GetUserConversationsPageParams) ([]GetUserConversationsPageRow, error) {
	rows, err := q.db.Query(ctx, getUserConversationsPage,
		arg.UserID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserConversationsPageRow
	for rows.Next() {
		var i GetUserConversationsPageRow
		if err := rows.Scan(
			&i.ConversationID,
			&i.CreatedAt,
			&i.Type,
			&i.MessageID,
			&i.MessageType,
			&i.MessageContent,
			&i.MessageCreatedAt,
			&i.MessageUserID,
			&i.MessageUserName,
			&i.MessageUserAvatar,
			&i.GroupAvatar,
			&i.GroupName,
			&i.OtherUserID,
			&i.OtherUserName,
			&i.OtherUserAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersByIDs = `-- name: GetUsersByIDs :many
SELECT id, name, avatar
FROM users
WHERE id = ANY($1::uuid[])
  AND deleted_at IS NULL
`

type GetUsersByIDsRow struct {
	ID     pgtype.UUID `json:"id"`
	Name   string      `json:"name"`
	Avatar pgtype.Text `json:"avatar"`
}

func (q *Queries) GetUsersByIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]GetUsersByIDsRow, error) {
	rows, err := q.db.Query(ctx, getUsersByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersByIDsRow
	for rows.Next() {
		var i GetUsersByIDsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Avatar); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const inviteToConversationAtomic = `-- name: InviteToConversationAtomic :one
INSERT INTO participants (id, conversation_id, user_id, created_at)
SELECT $1, c.id, u.id, NOW()
FROM conversations c
JOIN users u ON u.id = $2 AND u.deleted_at IS NULL
WHERE c.id = $3
  AND c.type = 0
  AND c.deleted_at IS NULL
ON CONFLICT DO NOTHING
RETURNING user_id
`

type InviteToConversationAtomicParams struct {
	ParticipantID  pgtype.UUID `json:"participant_id"`
	InviteeID      pgtype.UUID `json:"invitee_id"`
	ConversationID pgtype.UUID `json:"conversation_id"`
}

func (q *Queries) InviteToConversationAtomic(ctx context.Context, arg InviteToConversationAtomicParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, inviteToConversationAtomic, arg.ParticipantID, arg.InviteeID, arg.ConversationID)
	var user_id pgtype.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const isMember = `-- name: IsMember :one
SELECT EXISTS(
    SELECT 1 FROM participants
    WHERE conversation_id = $1 AND user_id = $2 AND deleted_at IS NULL
)
`

type IsMemberParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	UserID         pgtype.UUID `json:"user_id"`
}

func (q *Queries) IsMember(ctx context.Context, arg IsMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isMember, arg.ConversationID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isMemberOwner = `-- name: IsMemberOwner :one
SELECT EXISTS(
    SELECT 1 FROM conversations c
    JOIN participants p ON p.conversation_id = c.id AND p.user_id = $1
    WHERE c.id = $2
      AND c.type = 0
      AND c.owner_id = $1
      AND c.deleted_at IS NULL
      AND p.deleted_at IS NULL
)
`

type IsMemberOwnerParams struct {
	UserID         pgtype.UUID `json:"user_id"`
	ConversationID pgtype.UUID `json:"conversation_id"`
}

func (q *Queries) IsMemberOwner(ctx context.Context, arg IsMemberOwnerParams) (bool, error) {
	row := q.db.QueryRow(ctx, isMemberOwner, arg.UserID, arg.ConversationID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const leaveConversationAtomic = `-- name: LeaveConversationAtomic :execrows
UPDATE participants
SET deleted_at = NOW(), updated_at = NOW()
WHERE conversation_id = $1
  AND user_id = $2
  AND deleted_at IS NULL
`

type LeaveConversationAtomicParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	UserID         pgtype.UUID `json:"user_id"`
}

func (q *Queries) LeaveConversationAtomic(ctx context.Context, arg LeaveConversationAtomicParams) (int64, error) {
	result, err := q.db.Exec(ctx, leaveConversationAtomic, arg.ConversationID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const renameGroupConversation = `-- name: RenameGroupConversation :exec
UPDATE conversations
SET name = $1::text, avatar = $2::text, updated_at = NOW()
WHERE id = $3
  AND type = 0
  AND deleted_at IS NULL
`

type RenameGroupConversationParams struct {
	Name           string      `json:"name"`
	Avatar         string      `json:"avatar"`
	ConversationID pgtype.UUID `json:"conversation_id"`
}

func (q *Queries) RenameGroupConversation(ctx context.Context, arg RenameGroupConversationParams) error {
	_, err := q.db.Exec(ctx, renameGroupConversation, arg.Name, arg.Avatar, arg.ConversationID)
	return err
}

const storeConversation = `-- name: StoreConversation :exec

INSERT INTO conversations (id, type, name, avatar, owner_id)
VALUES ($1, $2, $3, $4, $5)
`

type StoreConversationParams struct {
	ID      pgtype.UUID `json:"id"`
	Type    int32       `json:"type"`
	Name    pgtype.Text `json:"name"`
	Avatar  pgtype.Text `json:"avatar"`
	OwnerID pgtype.UUID `json:"owner_id"`
}

// Conversation queries
func (q *Queries) StoreConversation(ctx context.Context, arg StoreConversationParams) error {
	_, err := q.db.Exec(ctx, storeConversation,
		arg.ID,
		arg.Type,
		arg.Name,
		arg.Avatar,
		arg.OwnerID,
	)
	return err
}

const storeMessageAndReturn = `-- name: StoreMessageAndReturn :one

WITH new_message AS (
    INSERT INTO messages (id, conversation_id, user_id, content, type, created_at)
    VALUES ($1, $2, $3, $4, $5, NOW())
    RETURNING id, type, created_at, conversation_id, content, user_id
)
SELECT
    nm.id, nm.type, nm.created_at, nm.conversation_id,
    nm.content as formatted_text,
    u.id as user_id, u.name as user_name, u.avatar as user_avatar
FROM new_message nm
JOIN users u ON u.id = nm.user_id
WHERE u.deleted_at IS NULL
`

type StoreMessageAndReturnParams struct {
	ID             pgtype.UUID `json:"id"`
	ConversationID pgtype.UUID `json:"conversation_id"`
	UserID         pgtype.UUID `json:"user_id"`
	Content        string      `json:"content"`
	Type           int32       `json:"type"`
}

type StoreMessageAndReturnRow struct {
	ID             pgtype.UUID        `json:"id"`
	Type           int32              `json:"type"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ConversationID pgtype.UUID        `json:"conversation_id"`
	FormattedText  string             `json:"formatted_text"`
	UserID         pgtype.UUID        `json:"user_id"`
	UserName       string             `json:"user_name"`
	UserAvatar     pgtype.Text        `json:"user_avatar"`
}

// Message queries
func (q *Queries) StoreMessageAndReturn(ctx context.Context, arg StoreMessageAndReturnParams) (StoreMessageAndReturnRow, error) {
	row := q.db.QueryRow(ctx, storeMessageAndReturn,
		arg.ID,
		arg.ConversationID,
		arg.UserID,
		arg.Content,
		arg.Type,
	)
	var i StoreMessageAndReturnRow
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.CreatedAt,
		&i.ConversationID,
		&i.FormattedText,
		&i.UserID,
		&i.UserName,
		&i.UserAvatar,
	)
	return i, err
}

const storeParticipant = `-- name: StoreParticipant :exec

INSERT INTO participants (id, conversation_id, user_id)
VALUES ($1, $2, $3)
`

type StoreParticipantParams struct {
	ID             pgtype.UUID `json:"id"`
	ConversationID pgtype.UUID `json:"conversation_id"`
	UserID         pgtype.UUID `json:"user_id"`
}

// Participant queries
func (q *Queries) StoreParticipant(ctx context.Context, arg StoreParticipantParams) error {
	_, err := q.db.Exec(ctx, storeParticipant, arg.ID, arg.ConversationID, arg.UserID)
	return err
}

const storeParticipantsBatch = `-- name: StoreParticipantsBatch :exec
INSERT INTO participants (id, conversation_id, user_id, created_at)
SELECT ids.participant_id, $1, uids.user_id, NOW()
FROM unnest($2::uuid[]) WITH ORDINALITY AS ids(participant_id, ord)
JOIN unnest($3::uuid[]) WITH ORDINALITY AS uids(user_id, ord) USING (ord)
`

type StoreParticipantsBatchParams struct {
	ConversationID pgtype.UUID   `json:"conversation_id"`
	ParticipantIds []pgtype.UUID `json:"participant_ids"`
	UserIds        []pgtype.UUID `json:"user_ids"`
}

func (q *Queries) StoreParticipantsBatch(ctx context.Context, arg StoreParticipantsBatchParams) error {
	_, err := q.db.Exec(ctx, storeParticipantsBatch, arg.ConversationID, arg.ParticipantIds, arg.UserIds)
	return err
}

const storeUser = `-- name: StoreUser :exec

INSERT INTO users (id, avatar, name, password, refresh_token)
VALUES ($1, $2, $3, $4, $5)
`

type StoreUserParams struct {
	ID           pgtype.UUID `json:"id"`
	Avatar       pgtype.Text `json:"avatar"`
	Name         string      `json:"name"`
	Password     string      `json:"password"`
	RefreshToken pgtype.Text `json:"refresh_token"`
}

// User queries
func (q *Queries) StoreUser(ctx context.Context, arg StoreUserParams) error {
	_, err := q.db.Exec(ctx, storeUser,
		arg.ID,
		arg.Avatar,
		arg.Name,
		arg.Password,
		arg.RefreshToken,
	)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET avatar = $2, name = $3, password = $4, refresh_token = $5, updated_at = NOW()
WHERE id = $1
`

type UpdateUserParams struct {
	ID           pgtype.UUID `json:"id"`
	Avatar       pgtype.Text `json:"avatar"`
	Name         string      `json:"name"`
	Password     string      `json:"password"`
	RefreshToken pgtype.Text `json:"refresh_token"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.ID,
		arg.Avatar,
		arg.Name,
		arg.Password,
		arg.RefreshToken,
	)
	return err
}
