// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	DeactivateConversation(ctx context.Context, id pgtype.UUID) error
	DeactivateParticipant(ctx context.Context, id pgtype.UUID) error
	FindParticipantByConversationAndUser(ctx context.Context, arg FindParticipantByConversationAndUserParams) (Participant, error)
	FindUserByUsername(ctx context.Context, name string) (User, error)
	// Complex queries for read model
	GetContacts(ctx context.Context, arg GetContactsParams) ([]GetContactsRow, error)
	GetConversationByID(ctx context.Context, id pgtype.UUID) (Conversation, error)
	GetConversationFull(ctx context.Context, arg GetConversationFullParams) (GetConversationFullRow, error)
	GetConversationMessagesWithUser(ctx context.Context, arg GetConversationMessagesWithUserParams) ([]GetConversationMessagesWithUserRow, error)
	GetDirectConversationBetweenUsers(ctx context.Context, arg GetDirectConversationBetweenUsersParams) (Conversation, error)
	GetGroupConversationByID(ctx context.Context, conversationID pgtype.UUID) (GroupConversation, error)
	GetGroupConversationByOwnerID(ctx context.Context, ownerID pgtype.UUID) ([]GetGroupConversationByOwnerIDRow, error)
	GetGroupConversationWithOwner(ctx context.Context, conversationID pgtype.UUID) (GetGroupConversationWithOwnerRow, error)
	GetMessageByID(ctx context.Context, id pgtype.UUID) (GetMessageByIDRow, error)
	GetMessagesForConversation(ctx context.Context, arg GetMessagesForConversationParams) ([]GetMessagesForConversationRow, error)
	GetNotificationMessageWithUser(ctx context.Context, id pgtype.UUID) (GetNotificationMessageWithUserRow, error)
	GetParticipantByID(ctx context.Context, id pgtype.UUID) (Participant, error)
	GetParticipantsByConversationID(ctx context.Context, arg GetParticipantsByConversationIDParams) ([]GetParticipantsByConversationIDRow, error)
	GetParticipantsForConversation(ctx context.Context, arg GetParticipantsForConversationParams) ([]GetParticipantsForConversationRow, error)
	GetParticipantsIDsByConversationID(ctx context.Context, conversationID pgtype.UUID) ([]pgtype.UUID, error)
	GetPotentialInvitees(ctx context.Context, arg GetPotentialInviteesParams) ([]GetPotentialInviteesRow, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByIDDTO(ctx context.Context, id pgtype.UUID) (GetUserByIDDTORow, error)
	GetUserConversations(ctx context.Context, arg GetUserConversationsParams) ([]GetUserConversationsRow, error)
	// Conversation queries
	StoreConversation(ctx context.Context, arg StoreConversationParams) error
	// GroupConversation queries
	StoreGroupConversation(ctx context.Context, arg StoreGroupConversationParams) error
	// Message queries
	StoreMessage(ctx context.Context, arg StoreMessageParams) error
	// Participant queries
	StoreParticipant(ctx context.Context, arg StoreParticipantParams) error
	// User queries
	StoreUser(ctx context.Context, arg StoreUserParams) error
	UpdateConversation(ctx context.Context, arg UpdateConversationParams) error
	UpdateGroupConversation(ctx context.Context, arg UpdateGroupConversationParams) error
	UpdateParticipant(ctx context.Context, arg UpdateParticipantParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpdateUserRefreshToken(ctx context.Context, arg UpdateUserRefreshTokenParams) error
}

var _ Querier = (*Queries)(nil)
