[[redirects]]
  from = "/api/*"
  to = "https://go-chat-23rpzgbtta-uc.a.run.app/:splat"
  status = 200

[[redirects]]
  from = "/ws"
  to = "https://go-chat-23rpzgbtta-uc.a.run.app/ws"
  status = 200
  
  
[[redirects]]
  from = "/*"
  to = "/"
  status = 200
