services:
  redis:
    image: redis:8.4.0-alpine
    restart: always
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./cache:/data

  postgres:
    image: postgres:18.1-alpine3.23
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - PGDATA=/pgdata
      - POSTGRES_PASSWORD=$DB_PASSWORD
    volumes:
      - ./db/pgdata:/pgdata
