package postgres

import (
	"context"
	"database/sql"
	"fmt"
	"log"

	"github.com/jackc/pgx/v5/pgxpool"
	_ "github.com/jackc/pgx/v5/stdlib"
	"github.com/pressly/goose/v3"
)

func RunMigrations(ctx context.Context, pool *pgxpool.Pool, migrationsDir string) error {
	config := pool.Config().ConnConfig
	connString := fmt.Sprintf("host=%s port=%d user=%s password=%s dbname=%s sslmode=disable",
		config.Host,
		config.Port,
		config.User,
		config.Password,
		config.Database,
	)

	db, err := goose.OpenDBWithDriver("pgx", connString)
	if err != nil {
		return fmt.Errorf("open database connection: %w", err)
	}
	defer func() {
		_ = db.Close()
	}()

	if err := goose.SetDialect("postgres"); err != nil {
		return fmt.Errorf("set dialect: %w", err)
	}

	if err := ensureGooseVersionTable(ctx, db); err != nil {
		return fmt.Errorf("ensure goose table: %w", err)
	}

	if err := goose.Up(db, migrationsDir); err != nil {
		return fmt.Errorf("run migrations: %w", err)
	}

	log.Printf("✅ Migrations ran successfully from %s", migrationsDir)

	return nil
}

func ensureGooseVersionTable(ctx context.Context, db *sql.DB) error {
	tableName := goose.TableName()
	query := "SELECT EXISTS ( SELECT 1 FROM pg_tables WHERE (current_schema() IS NULL OR schemaname = current_schema()) AND tablename = $1 )"

	var exists bool
	if err := db.QueryRowContext(ctx, query, tableName).Scan(&exists); err != nil {
		return fmt.Errorf("check version table: %w", err)
	}
	if exists {
		return nil
	}

	createQuery := fmt.Sprintf(`CREATE TABLE %s (
		id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
		version_id bigint NOT NULL,
		is_applied boolean NOT NULL,
		tstamp timestamp NOT NULL DEFAULT now()
	)`, tableName)
	insertQuery := fmt.Sprintf("INSERT INTO %s (version_id, is_applied) VALUES ($1, $2)", tableName)

	tx, err := db.BeginTx(ctx, nil)
	if err != nil {
		return fmt.Errorf("begin version table: %w", err)
	}
	if _, err := tx.ExecContext(ctx, createQuery); err != nil {
		_ = tx.Rollback()
		return fmt.Errorf("create version table: %w", err)
	}
	if _, err := tx.ExecContext(ctx, insertQuery, int64(0), true); err != nil {
		_ = tx.Rollback()
		return fmt.Errorf("seed version table: %w", err)
	}
	if err := tx.Commit(); err != nil {
		return fmt.Errorf("commit version table: %w", err)
	}
	return nil
}
