name: Back

on:
  push:
    branches: [main]
    paths:
      - backend/**
      - .github/workflows/back.yml

env:
  IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_NAME }}:${{ github.run_number }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run tests
        run: go test ./...

      - name: Build Container
        run: docker build --target prod -t $IMAGE_NAME .

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Authorize Docker push
        if: github.ref == 'refs/heads/main'
        run: gcloud auth configure-docker

      - name: Push Container
        if: github.ref == 'refs/heads/main'
        run: docker push $IMAGE_NAME

  deploy:
    name: Deploy
    if: github.ref == 'refs/heads/main'
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0.4.0
        with:
          service: ${{ secrets.GCP_APP_NAME }}
          image: ${{ env.IMAGE_NAME }}
          region: us-central1
          credentials: ${{ secrets.GCP_SA_KEY }}

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
