name: Back

on:
  push:
    branches: [main]
    paths:
      - server/**
      - .github/workflows/**

env:
  IMAGE_NAME: chat

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run tests
        run: go test ./...

      - name: Build Container
        run: docker build --target prod -t $IMAGE_NAME .
